### ISSUE TITLE
Credits pls? | Mind the License! 

### ISSUE THREAD

**Issue by Tomato6966** [kabirsingh2004/Discord-Youtube-poster-#1]
Credits pls?
UwU

**Comment by KabirJaipal** [comment]
Oo sorry i forgot
Sorry i give credit

**Comment by Tomato6966** [comment]
Thanks could u change it to saying Thanks for @Tomato6966 by making [discord-yt-poster](https://npmjs.org/discord-yt-poster) which i am using!

**Comment by Tomato6966** [comment]
+ thanks for the cool repo
